server:
  port: 8083
spring:
  application:
    name: factory-service # 服务名称（消费者将通过此名称调用)
    #name: user-service # 相同服务名测试负载均衡
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/ #注册到Eureka Server地址
    instances:
      prefer-ip-address: true #注册时用ip
